### ISSUE TITLE
5. Adjustable grain size for the FFT

### ISSUE THREAD

**Issue by spr13** [HPCE/hpce-2016-cw2#11]
I do not really understand what we are are suppose to do in this step.
I currently have something that looks like:

```
void my_recursive_function(some_type x)
{
           //do some things on x//

           tbb::task_group group;

            group.run([&](){my_recursive_function(param1);});
            group.run([&](){my_recursive_function(param2);});
            group.wait();
}
```

So if I understand correctly I have something that expands like a binary tree of parallel work,
and HPCE_FFT_RECURSION_K has to limit the tree to a certain size/width.
So I need a some kind of counter that counts up every time I call the recursion function and once I reach a certain amount relative to K I should parallelizing the recursion.

```
K=2  would look like                    K=4 would look like

            |                                        |    
           / \                                     /   \
          |   |                                  / \   / \
          |   |                                 |   |  |  |
```
Is that correct?

**Comment by m8pple** [comment]
The grain size is trying to control the point at which you stop splitting. So you stop
creating parallel work when the amount left in the tree is <=K.  I think what you
are proposing is to limit on the way down, so that you stop after K splits.

The argument against this is about what happens if you have P processors. If
you choose K=4 and P>>4, then it will not create enough parallel tasks. If
you choose K=1024 (to try to cover an system), but the problem is not that
big (e.g. n=2048), then you have split too much as each task will be too small
(too much overhead).

So, using the example from above:

```
n=4

K=4 would look like      K=2  would look like        K=1 would look like

            |                     |                           |    
        Seq[4]                   / \                        /   \
                           Seq[2]   Seq[2]                /  \ /  \
                                                         S1 S1 S1 S1


=========================================================================

n=2

K=4 would look like      K=2  would look like        K=1 would look like

            |                     |                           |    
        Seq[2]                  Seq[2]                       / \
                                                            S1 S1


```

**Comment by spr13** [comment]
Thank you. It does make much more sense.
I made the modifications to my code, I got some weird values for my graph but I think it is doing what it is suppose to do.
