### ISSUE TITLE
Setup and renaming steps cause make to return errors

### ISSUE THREAD

**Issue by majpoynton** [HPCE/hpce-2016-cw2#12]
> Also make sure that the factory function is declared as std::shared_ptr<fourier_transform> hpce::your_login::Create_direct_fourier_transform_parfor_inner(), both in src/your_login/direct_fourier_transform_parfor_inner.cpp, and in src/fourier_transform_register_factories.cpp

If I do the above, it causes make to return errors ("explicit qualification in declaration"); is the above correct, because it's the first time it's mentioned, but I feel like we were supposed to already have noticed and done it by the phrasing.

Also, when you say

> As part of the modifications, you probably noticed a function at the bottom of the file called std::shared_ptr<fourier_transform> Create_direct_fourier_transform(), and (hopefully!) modified to std::shared_ptr<fourier_transform> Create_direct_fourier_transform_parfor_inner(). 

presumably you don't also want us to modify

> return std::make_shared\<direct_fourier_transform>()

to

> return std::make_shared\<direct_fourier_transform_parfor_inner>()

as that also causes an error ("template argument 1 is invalid"). If that's correct and we should just modify the function name, I'm not quite sure what the function does. Or doesn't it matter that much?

Thanks!

**Comment by patengelbert** [comment]
The "explicit qualification in declaration" means that there is a problem with your class definition. Have a look that your namespace and class definition is correct. It should be something like:
`namespace hpce
{
	namespace pe313
	{
		class direct_fourier_transform_parfor_inner
'
`
but without seeing your code, I can't help much more.

The template argument error occurs if you do not change 
`return std::make_shared<direct_fourier_transform>()`
to
`return std::make_shared<direct_fourier_transform_parfor_inner>()`
Note the top error (ignore the warnings) if I make this change
`src/pe313/direct_fourier_transform_parfor_inner.cpp:79:28: error: ‘direct_fourier_transform’ was not declared in this scope
    return std::make_shared<direct_fourier_transform>();`

This function creates a shared pointer to the implementation of the DFT. It allows the rest of the program to find this implemetation via this pointer. If you have the wrong class attached, it will try to make a pointer to the *normal* DFT rather than the one that you modified.

Hope this helps.
Try reading error messages from top to bottom, the later ones tend to be caused by those before.

**Comment by m8pple** [comment]
@patengelbert 's explanation is correct.

Is it the phrasing that is confusing, or the ordering?

I positioned it as a more descriptive unit of things to be done and
patterns to be modified, rather than an explicit enumerated list of
things to be done. Part of the idea is that those who are less familiar
with C++ will come across some aspects of dynamic factories, in
a reasonably safe setting, and the idea of having multiple implementations
you can switch between.

**Comment by majpoynton** [comment]
Very helpful, thank you both. It was just my lack of confidence in changing something that I didn't understand, even though it didn't make sense not to change it.
