### ISSUE TITLE
No Pivot Charts in Mac Excel

### ISSUE THREAD

**Issue by nar213** [HPCE/hpce-2016-cw2#19]
Just a warning to any macOS users out there, you will not be able to find the "Pivot Chart" feature in Microsoft Excel because it is not supported.

**Comment by m8pple** [comment]
Wow, seriously? It's been one of the basic spreadsheet features in Excel
for years now, it didn't even occur to me to check.

Does it support pivot tables at least (even if not the charts)?

**Comment by nar213** [comment]
Fortunately pivot tables are an available option.

**Comment by m8pple** [comment]
When you say grand total, is that the one at the bottom of each chunk size column?
That one would not work, as the auto-timer scales the max n according to execution time.

_Note_: I'm not looking at the spec right now, so can't remember what I asked
you to look at in relation to this data, it is more just what I would be inclined to do.

So I think more the latter, but for example with a few selected N values.
For example, given this data-set I would be interested in putting chunk size on X, then
select some specific N values, e.g. binary powers from 64 up to 4096 look
interesting.

**Comment by nar213** [comment]
Indeed, however I did trim data such that it went to same max-n. I will admit it doesn't give enough granular detail but it gives quite a good overview with a clear pattern.

**Comment by jeremych1000** [comment]
Can I just confirm if we do scale it to the same max-n we can plot Total Time (s) on the pivotchart? It's what Excel defaults to and the graphs look alright ... :p

**Comment by m8pple** [comment]
Sorry, didn't see the extra activity on this issue.

Using the same max-n is showing something slightly different to plotting
individual n. It is effectively defining a benchmark consisting of all n's up
to that point. The problem is that it is an equally weighted benchmark,
so the time of the biggest n contributes the same as the smallest n. So
if there is large performance variation for small/medium n, it will be
swamped by the largest n.

This could be a valid approach, but effectively it is saying "I _only_ care
about the largest n", in which case there is not much point including
all the smaller ones as well.

Plotting individual n values allows you to see the different performance
properties as n changes - so is the best value of K actually dependent
on the value of n?

I don't mind too much if you've already done the graphs, but the takeaway
idea is to think about different scales, and how performance/tuning might
vary at those difference scales.
