### ISSUE TITLE
Test #34: check ... 3.5810590664 is more than 1.1., FAIL

### ISSUE THREAD

**Issue by hamish-milne** [HPCE/hpce-2016-cw2#34]
```
hnm13, 34, Timing hpce.hnm13.fast_fourier_transform_parfor with 4 CPUs and n=2^24: check observed parallelism (totalTime/wallTime) of 16 3.5810590664 is more than 1.1., FAIL
```

The observed parallelism of 3.58 is pretty close to the ideal value of 4, and certainly more than the 1.1 required by the test. My guess is that "16 3.58..." (the '16' doesn't appear in test 33 or 35) doesn't compare properly with 1.1.

**Comment by jeremych1000** [comment]
```
jc4913, 39, For 4 CPUs, n=2^22, fast: check time for taskgroup (0.4851535770) is no more than 0.9x that of combined (0.4287281960)., FAIL
```

I've got similar problems - 0.48/0.42 = 1.13x, but shouldn't taskgroup be slower than combined? Does it mean to be the speedup from taskgroup -> combined should be great than 1/0.9x?

**Comment by m8pple** [comment]
The 16 is definitely causing problems. Where might it be coming from...?

Also, the 1.1 is chosen because it is relatively hard to get a good speedup on
the fast fourier transform with parfor, at least the way that we're doing
it there. There is a large amount of non-parallel work for the values less
than k, which tends to limit the speedup, so a speed-up of 3.58x is quite
impressive (even odd) on a 4-core machine.

Between the taskgroup and the parfor techniques, you'll generally find
the taskgroup is much more effective. So your combined version should
be aiming to get a good speed-up for large n, but avoid any slow-down
for medium/small n. You may want to revisit your default tuning parameters
for combined, esp. for the parfor bit.

**Comment by hamish-milne** [comment]
.. Oh, of course. I accidentally left in a printf in _parfor and evidently it found its way into the test framework. My bad!
