### ISSUE TITLE
Very high sys time causing test 34 to fail

### ISSUE THREAD

**Issue by majpoynton** [HPCE/hpce-2016-cw2#39]
![image](https://cloud.githubusercontent.com/assets/9308721/19860462/a8b66632-9f80-11e6-85e9-b4395c780524.png)

As shown above, I get an unreasonably high sys time for fast_fourier_transform_parfor. It's the only one I have this problem with, and I've carefully checked it for random typos against my other files.

Here's an strace if it helps:
![image](https://cloud.githubusercontent.com/assets/9308721/19860630/4cf10c98-9f81-11e6-88d9-c1b937769995.png)

Does anyone have an idea about what might cause this?
Thanks!

**Comment by m8pple** [comment]
Thanks for the strace, it's quite useful:
- the [futex](https://en.wikipedia.org/wiki/Futex) you can see is a locking primitive used in
   linux to do user-space locking.
- the call to [sched_yield](http://man7.org/linux/man-pages/man2/sched_yield.2.html) is
  used to indicate to the OS that a thread is giving up its timeslice because it has nothing
  to do.

So my guess is that you have K set too low, so there are very large numbers of small
tasks. The worker threads of TBB do something like:

     while(1){
         if(get_task()){
            execute_task();
         }else{
            sched_yield();
         }
     }

so I think you're seeing threads spending a lot of time spinning then getting
small tasks.

**Comment by majpoynton** [comment]
That was it, thank you! Very good information.
